FROM python:3.8-slim
RUN pip install flask -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY incubator_simulation.py /app/incubator_simulation.py
WORKDIR /app
EXPOSE 5005
CMD ["python", "incubator_simulation.py"]
